# Security Configuration for CI/CD Pipeline
# This file defines security policies and thresholds for the project

security:
  # SAST Configuration
  sast:
    tools:
      - trivy
      - semgrep
      - codeql
      - bandit
      - safety
      - hadolint
    
    thresholds:
      critical: 0
      high: 5
      medium: 20
      low: 50
    
    fail_on:
      - critical
      - high
  
  # DAST Configuration
  dast:
    tools:
      - owasp-zap
      - nuclei
      - nikto
    
    thresholds:
      critical: 0
      high: 3
      medium: 10
      low: 25
    
    fail_on:
      - critical
      - high
  
  # Infrastructure Security
  infrastructure:
    tools:
      - checkov
      - tfsec
    
    thresholds:
      critical: 0
      high: 5
      medium: 15
      low: 30
    
    fail_on:
      - critical
      - high
  
  # Container Security
  container:
    tools:
      - trivy
      - docker-scout
    
    thresholds:
      critical: 0
      high: 3
      medium: 10
      low: 20
    
    fail_on:
      - critical
      - high
  
  # Dependency Security
  dependencies:
    tools:
      - snyk
      - npm-audit
      - safety
    
    thresholds:
      critical: 0
      high: 5
      medium: 15
      low: 30
    
    fail_on:
      - critical
      - high

# Security Gates
gates:
  development:
    required_scans:
      - sast
      - dependency-security
      - infrastructure-security
  
  staging:
    required_scans:
      - sast
      - dast
      - container-security
      - dependency-security
      - infrastructure-security
  
  production:
    required_scans:
      - sast
      - dast
      - container-security
      - dependency-security
      - infrastructure-security
    manual_approval: true

# Notification Configuration
notifications:
  slack:
    webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    channels:
      - security-alerts
      - devops-team
  
  email:
    recipients:
      - security-team@company.com
      - devops-team@company.com
  
  github:
    security_advisories: true
    dependabot: true
    code_scanning: true
