# tfsec Configuration
# This file configures tfsec security scanning for Terraform

minimum_severity: MEDIUM
exclude_rule_ids:
  # Exclude specific rules that might be false positives
  - AWS001  # S3 Bucket should have versioning enabled
  - AWS002  # S3 Bucket should not have public read access

include_rule_ids:
  # Include specific high-priority rules
  - AWS003  # S3 Bucket should not have public write access
  - AWS004  # S3 Bucket should have server-side encryption enabled
  - AWS005  # S3 Bucket should not have public ACL

severity_overrides:
  AWS001: LOW
  AWS002: HIGH

exclude_directories:
  - .git
  - .terraform
  - node_modules
